workflows:
  ios-build:
    name: iOS Build (Expo EAS)
    environment:
      node: 20
      npm: default
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Build iOS app
        script: |
          eas build --platform ios --profile development --non-interactive
    artifacts:
      - '**/*.ipa'
