workflows:
  ios-build:
    name: iOS Build
    environment:
      node: 20
      npm: 10.7.0
      xcode: 16.4
      groups:
        - expo  # <-- qui specifichi il tuo gruppo expo

    scripts:
      - name: Install EAS CLI
        script: npm install -g eas-cli

      - name: Install dependencies
        script: npm install

      - name: Login to Expo
        script: eas whoami || eas login --token $EXPO_TOKEN

      - name: Build iOS App
        script: eas build --platform ios --profile development --non-interactive

    artifacts:
      - '**/*.ipa'
